
services:
  # Citus Coordinator node (master)
  citus_master:
    image: citusdata/citus:13.0.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
      CITUS_NODE_NAME: citus_master
    volumes:
      - citus_master_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twitter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Citus Worker nodes
  citus_worker_1:
    image: citusdata/citus:13.0.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
      CITUS_NODE_NAME: citus_worker_1
    volumes:
      - citus_worker1_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    depends_on:
      - citus_master
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twitter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  citus_worker_2:
    image: citusdata/citus:13.0.3
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
      CITUS_NODE_NAME: citus_worker_2
    volumes:
      - citus_worker2_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    depends_on:
      - citus_master
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twitter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  citus_worker_3:
    image: citusdata/citus:13.0.3
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
      CITUS_NODE_NAME: citus_worker_3
    volumes:
      - citus_worker3_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    depends_on:
      - citus_master
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twitter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ for async processing
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  citus_master_data:
  citus_worker1_data:
  citus_worker2_data:
  citus_worker3_data: