
services:
  # Citus Coordinator (master)
  citus_master:
    image: citusdata/citus:13.0.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
    volumes:
      - citus_master_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twitter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Citus Workers
  citus_worker_1:
    image: citusdata/citus:13.0.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
    volumes:
      - citus_worker1_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    depends_on:
      - citus_master

  citus_worker_2:
    image: citusdata/citus:13.0.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
    volumes:
      - citus_worker2_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    depends_on:
      - citus_master

  citus_worker_3:
    image: citusdata/citus:13.0.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
    volumes:
      - citus_worker3_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    depends_on:
      - citus_master

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: step3_async_feed/Dockerfile
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@citus_master/twitter_db
      DATABASE_URL_SYNC: postgresql://user:password@citus_master/twitter_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      citus_master:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: uvicorn step3_async_feed.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ..:/app

volumes:
  citus_master_data:
  citus_worker1_data:
  citus_worker2_data:
  citus_worker3_data: