services:
  # Regular PostgreSQL (single node)
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twitter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: step1_basic/Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres/twitter_db
      DATABASE_URL_SYNC: postgresql://user:password@postgres/twitter_db
      DB_TYPE: postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn step1_basic.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ..:/app

volumes:
  postgres_data: